apiVersion: 1

datasources:
  - name: Prometheus-Central
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false  # SRE best practice: configuration is locked in code
