apiVersion: v2
name: monitoring-stack
description: Corporate SRE Observability Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "51.2.0" # Current stable in 2026
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki-stack
    version: "2.9.11"
    repository: "https://grafana.github.io/helm-charts"
